lib/paymongo_example_web/router.ex
defmodule PaymongoExampleWeb.Router do
  use PaymongoExampleWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_live_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  pipeline :app do
    plug(:put_layout, {PaymongoExampleWeb.LayoutView, :app})
  end

  pipeline :admin do
    plug(:put_layout, {PaymongoExampleWeb.LayoutView, :admin})
  end

  pipeline :root do
    plug(:put_root_layout, {PaymongoExampleWeb.LayoutView, :root})
  end

  scope "/", PaymongoExampleWeb do
    pipe_through [:browser, :root]

    live "/", HomeLive.Index, as: :home_index
    live "/:slug/show", HomeLive.Show, as: :home_show
  end

  scope "/", PaymongoExampleWeb do
    pipe_through [:browser, :root, :app]
    get "/:payment_type/success", RedirectController, :success
    get "/:payment_type/failed", RedirectController, :failed
  end

  scope "/admin", PaymongoExampleWeb.Admin do
    pipe_through [:browser, :root, :admin]

    if Mix.env() == :dev do
      scope "/" do
        live_dashboard "/dashboard"
      end
    end

    get "/", PageController, :index
    live "/live-dashboard", DashboardLive, as: :dashboard
    resources "/items", ItemController
  end

  # Other scopes may use custom stacks.
  scope "/api", PaymongoExampleWeb do
    pipe_through :api
    post "/shoppers-hub-webhooks", WebhookController, :webhooks
  end
end

lib/paymongo_example_web/views/shared_view.ex
defmodule PaymongoExampleWeb.SharedView do
  use PaymongoExampleWeb, :view
end

lib/paymongo_example_web/templates/shared/_footer.html.eex
<div class="footer bg-red-100 py-5 px-5">
  Footer 
</div>  

lib/paymongo_example_web/templates/shared/_home-footer.html.eex
<footer class="container mx-auto bg-white py-8 border-t border-gray-400">
  <div class="container flex px-3 py-8 ">
    <div class="w-full mx-auto flex flex-wrap">
      <div class="flex w-full lg:w-1/2 ">
        <div class="px-3 md:px-0">
          <h3 class="font-bold text-gray-900">About</h3>
          <p class="py-4">
            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas vel mi ut felis tempus commodo nec id erat. Suspendisse consectetur dapibus velit ut lacinia.
          </p>
        </div>
      </div>
      <div class="flex w-full lg:w-1/2 lg:justify-end lg:text-right">
        <div class="px-3 md:px-0">
          <h3 class="font-bold text-gray-900">Social</h3>
          <ul class="list-reset items-center pt-3">
            <li>
              <a class="inline-block no-underline hover:text-black hover:underline py-1 text-3xl" href="#"><i class="fab fa-facebook-square"></i></a>
              <a class="inline-block no-underline hover:text-black hover:underline py-1 text-3xl" href="#"><i class="fab fa-instagram-square"></i></a>
              <a class="inline-block no-underline hover:text-black hover:underline py-1 text-3xl" href="#"><i class="fab fa-twitter-square"></i></a>
              <a class="inline-block no-underline hover:text-black hover:underline py-1 text-3xl" href="#"><i class="fab fa-linkedin"></i></a>
            </li>
          </ul>
        </div>
      </div>
    </div>
  </div>
</footer>

lib/paymongo_example_web/templates/shared/_nav-header.html.eex
<nav id="header" class="w-full z-30 top-0 py-1">
  <div class="w-full container mx-auto flex flex-wrap items-center justify-between mt-0 px-6 py-3">

    <label for="menu-toggle" class="cursor-pointer md:hidden block">
      <svg class="fill-current text-gray-900" xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 20 20">
        <title>menu</title>
        <path d="M0 3h20v2H0V3zm0 6h20v2H0V9zm0 6h20v2H0v-2z"></path>
      </svg>
    </label>
    <input class="hidden" type="checkbox" id="menu-toggle" />

    <div class="hidden md:flex md:items-center md:w-auto w-full order-3 md:order-1" id="menu">
      <nav>
        <ul class="md:flex items-center justify-between text-base text-gray-700 pt-4 md:pt-0">
          <li><a class="inline-block no-underline hover:text-black hover:underline py-2 px-4" href="#">Shop</a></li>
          <li><a class="inline-block no-underline hover:text-black hover:underline py-2 px-4" href="#">About</a></li>
        </ul>
      </nav>
    </div>

    <div class="order-1 md:order-2">
      <a class="flex items-center tracking-wide no-underline hover:no-underline font-bold text-gray-800 text-xl " href="#">
        <svg class="fill-current text-gray-800 mr-2" xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24">
          <path d="M5,22h14c1.103,0,2-0.897,2-2V9c0-0.553-0.447-1-1-1h-3V7c0-2.757-2.243-5-5-5S7,4.243,7,7v1H4C3.447,8,3,8.447,3,9v11 C3,21.103,3.897,22,5,22z M9,7c0-1.654,1.346-3,3-3s3,1.346,3,3v1H9V7z M5,10h2v2h2v-2h6v2h2v-2h2l0.002,10H5V10z" />
        </svg>
        SHOPPER'S HUB
      </a>
    </div>
    <div class="order-2 md:order-3 flex items-center" id="nav-content">

      <a class="inline-block no-underline hover:text-black" href="#">
        <svg class="fill-current hover:text-black" xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24">
          <circle fill="none" cx="12" cy="7" r="3" />
          <path d="M12 2C9.243 2 7 4.243 7 7s2.243 5 5 5 5-2.243 5-5S14.757 2 12 2zM12 10c-1.654 0-3-1.346-3-3s1.346-3 3-3 3 1.346 3 3S13.654 10 12 10zM21 21v-1c0-3.859-3.141-7-7-7h-4c-3.86 0-7 3.141-7 7v1h2v-1c0-2.757 2.243-5 5-5h4c2.757 0 5 2.243 5 5v1H21z" />
        </svg>
      </a>

      <a class="pl-3 inline-block no-underline hover:text-black" href="#">
        <svg class="fill-current hover:text-black" xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24">
          <path d="M21,7H7.462L5.91,3.586C5.748,3.229,5.392,3,5,3H2v2h2.356L9.09,15.414C9.252,15.771,9.608,16,10,16h8 c0.4,0,0.762-0.238,0.919-0.606l3-7c0.133-0.309,0.101-0.663-0.084-0.944C21.649,7.169,21.336,7,21,7z M17.341,14h-6.697L8.371,9 h11.112L17.341,14z" />
          <circle cx="10.5" cy="18.5" r="1.5" />
          <circle cx="17.5" cy="18.5" r="1.5" />
        </svg>
      </a>
    </div>
  </div>
</nav>

lib/paymongo_example_web/templates/shared/_sidenav.html.eex
<nav class="navbar">
  <ul class="navbar-nav">
    <!-- Admin Logo --> 
    <li class="logo">
      <a href="/admin" class="nav-link">
        <span class="link-text logo-text">Admin</span>
        <svg
          aria-hidden="true"
          focusable="false"
          data-prefix="fad"
          data-icon="angle-double-right"
          role="img"
          xmlns="http://www.w3.org/2000/svg"
          viewBox="0 0 448 512"
          class="svg-inline--fa fa-angle-double-right fa-w-14 fa-5x"
          >
          <g class="fa-group">
          <path
            fill="currentColor"
            d="M224 273L88.37 409a23.78 23.78 0 0 1-33.8 0L32 386.36a23.94 23.94 0 0 1 0-33.89l96.13-96.37L32 159.73a23.94 23.94 0 0 1 0-33.89l22.44-22.79a23.78 23.78 0 0 1 33.8 0L223.88 239a23.94 23.94 0 0 1 .1 34z"
            class="fa-secondary"
            ></path>
          <path
            fill="currentColor"
            d="M415.89 273L280.34 409a23.77 23.77 0 0 1-33.79 0L224 386.26a23.94 23.94 0 0 1 0-33.89L320.11 256l-96-96.47a23.94 23.94 0 0 1 0-33.89l22.52-22.59a23.77 23.77 0 0 1 33.79 0L416 239a24 24 0 0 1-.11 34z"
            class="fa-primary"
            ></path>
          </g>
        </svg>
      </a>
    </li>
    <!-- end Admin Logo --> 

    <!-- Items --> 
    <li class="nav-item">
      <a href="<%= Routes.item_path(@conn, :index) %>" class="nav-link">
        <svg 
          aria-hidden="true" 
          focusable="false" 
          data-prefix="fas" 
          data-icon="shopping-cart" 
          class="svg-inline--fa fa-shopping-cart fa-w-18" 
          role="img" 
          xmlns="http://www.w3.org/2000/svg" 
          viewBox="0 0 576 512">
          <path 
            fill="currentColor" 
            d="M528.12 301.319l47.273-208C578.806 78.301 567.391 64 551.99 64H159.208l-9.166-44.81C147.758 8.021 137.93 0 126.529 0H24C10.745 0 0 10.745 0 24v16c0 13.255 10.745 24 24 24h69.883l70.248 343.435C147.325 417.1 136 435.222 136 456c0 30.928 25.072 56 56 56s56-25.072 56-56c0-15.674-6.447-29.835-16.824-40h209.647C430.447 426.165 424 440.326 424 456c0 30.928 25.072 56 56 56s56-25.072 56-56c0-22.172-12.888-41.332-31.579-50.405l5.517-24.276c3.413-15.018-8.002-29.319-23.403-29.319H218.117l-6.545-32h293.145c11.206 0 20.92-7.754 23.403-18.681z"
            class="fa-secondary" 
            ></path>
          <path 
            fill="currentColor" 
            d="M528.12 301.319l47.273-208C578.806 78.301 567.391 64 551.99 64H159.208l-9.166-44.81C147.758 8.021 137.93 0 126.529 0H24C10.745 0 0 10.745 0 24v16c0 13.255 10.745 24 24 24h69.883l70.248 343.435C147.325 417.1 136 435.222 136 456c0 30.928 25.072 56 56 56s56-25.072 56-56c0-15.674-6.447-29.835-16.824-40h209.647C430.447 426.165 424 440.326 424 456c0 30.928 25.072 56 56 56s56-25.072 56-56c0-22.172-12.888-41.332-31.579-50.405l5.517-24.276c3.413-15.018-8.002-29.319-23.403-29.319H218.117l-6.545-32h293.145c11.206 0 20.92-7.754 23.403-18.681z"
            class="fa-primary" 
            ></path>
        </svg>
        <span class="link-text">Items</span>
      </a>
    </li>
    <!-- end Items --> 




    <!-- Logout --> 
    <li class="nav-item">
      <a href="#" class="nav-link">
        <svg
          aria-hidden="true"
          focusable="false"
          data-prefix="fad"
          data-icon="space-shuttle"
          role="img"
          xmlns="http://www.w3.org/2000/svg"
          viewBox="0 0 640 512"
          class="svg-inline--fa fa-space-shuttle fa-w-20 fa-5x"
          >
          <g class="fa-group">
          <path
            fill="currentColor"
            d="M32 416c0 35.35 21.49 64 48 64h16V352H32zm154.54-232h280.13L376 168C243 140.59 222.45 51.22 128 34.65V160h18.34a45.62 45.62 0 0 1 40.2 24zM32 96v64h64V32H80c-26.51 0-48 28.65-48 64zm114.34 256H128v125.35C222.45 460.78 243 371.41 376 344l90.67-16H186.54a45.62 45.62 0 0 1-40.2 24z"
            class="fa-secondary"
            ></path>
          <path
            fill="currentColor"
            d="M592.6 208.24C559.73 192.84 515.78 184 472 184H186.54a45.62 45.62 0 0 0-40.2-24H32c-23.2 0-32 10-32 24v144c0 14 8.82 24 32 24h114.34a45.62 45.62 0 0 0 40.2-24H472c43.78 0 87.73-8.84 120.6-24.24C622.28 289.84 640 272 640 256s-17.72-33.84-47.4-47.76zM488 296a8 8 0 0 1-8-8v-64a8 8 0 0 1 8-8c31.91 0 31.94 80 0 80z"
            class="fa-primary"
            ></path>
          </g>
        </svg>
        <span class="link-text">Logout</span>
      </a>
    </li> 
    <!-- Logout --> 
  </ul>
</nav>

lib/paymongo_example_web/templates/shared/_topnav.html.eex
<div class="flex bg-white py-5 px-5">
  Shopper's Hub 
</div>  